paths:
  /products:
    get:
      summary: Returns products (object:[]) collection
      tags:
        - Products
      responses:
        '200':
          description: Response succesfull, products payload
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        '500':
          description: Server error
    post:
      summary: Creates a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct'
      responses:
        '201':
          description: Product created succesfully
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
  /products/{pid}:
    get:
      summary: Returns one product
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to find
          schema:
            $type: string
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        '500':
          description: Server error
    put:
      summary: Update product fields with id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to update
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        '200':
          description: Price and title was succesfully updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/PutProduct'
        '500':
          description: Server error
    delete:
      summary: Delete one product
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to delete
          schema:
            $type: string
      responses:
        '204':
          description: Product deleted succesfully
components:
  schemas:
    Success:
      type: object
      properties:
        status:
          type: string
          description: success || error
        message:
          type: string
          description: Response description
      example:
        status: success
        message: Product updated
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated id by mongoDB
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Brief product description
        category:
          type: string
          description: Product category
        price:
          type: number
          description: Product price
        thumbnail:
          type: string
          description: Product image (URL)
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product actual stock
        Status:
          type: Bool
          description: Product status condition
      example:
        _id: 'new ObjectId("64e899e3cc1ce6dfbf312e0a")'
        title: 'Table'
        description: 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support'
        category: 'Bespoke'
        price: 11.99
        thumbnail: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/284.jpg'
        code: 'n1aYH'
        stock: 50
        status: 'true'
    PutProduct:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated id by mongoDB
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Brief product description
        category:
          type: string
          description: Product category
        price:
          type: number
          description: Product price
        thumbnail:
          type: string
          description: Product image (URL)
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product actual stock
        Status:
          type: Bool
          description: Product status condition
      example:
        _id: 'new ObjectId("64e899e3cc1ce6dfbf312e0a")'
        title: 'Coffe table'
        description: 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support'
        category: 'Bespoke'
        price: 39.99
        thumbnail: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/284.jpg'
        code: 'n1aYH'
        stock: 50
        status: 'true'
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Brief product description
        category:
          type: string
          description: Product category
        price:
          type: number
          description: Product price
        thumbnail:
          type: string
          description: Product image (URL)
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product actual stock
        Status:
          type: Bool
          description: Product status condition
      example:
        title: 'Table'
        description: 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support'
        category: 'Bespoke'
        price: 11.99
        thumbnail: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/284.jpg'
        code: 'n1aYH'
        stock: 50
        status: 'true'
    updateProduct:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated id by mongoDB
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Brief product description
        category:
          type: string
          description: Product category
        price:
          type: number
          description: Product price
        thumbnail:
          type: string
          description: Product image (URL)
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product actual stock
        Status:
          type: Bool
          description: Product status condition
      example:
        title: 'Coffe table'
        price: 39.99
